<?php
/*
Jorge - frontend for mod_logdb - ejabberd server-side message archive module.

Copyright (C) 2008 Zbigniew Zolkiewski

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

*/
require("func.php");
require("lang.php");
require("class.sessions.php");
require("class.ejabberd_xmlrpc.php");
require("class.roster.php");
require("config.php");

ob_start();

// init session
$sess = new session;

// RPC server redundancy
$rpc_host = check_rpc_server($rpc_arr,$rpc_port);

// in case no RPC servers are available stop jorge
if ($rpc_host===false) {

		print "<br><center><b>Currently service is unavailable. Please try again later.</b></center>";
		exit;
	}

$ejabberd_rpc = new rpc_connector("$rpc_host","$rpc_port","$xmpp_host_dotted");

if (check_registered_user($sess,$ejabberd_rpc,$xmpp_host) !== true) { header("Location: index.php?act=logout"); exit; }

// connect to mod_logdb
db_connect(MYSQL_HOST,MYSQL_USER,MYSQL_PASS,MYSQL_NAME);

define(TOKEN,$sess->get('uid_l'));
define(USER_ID, get_user_id(TOKEN,$xmpp_host));

if (!ctype_digit(USER_ID)) { exit; }

$e_string=$_GET['a'];

if ($e_string) {
		$variables = decode_url2($e_string,TOKEN,$url_key);
		$tslice = $variables[tslice];
		$talker = $variables[talker];
		$server = $variables[server];
	}
	else {
		header('Location: main.php');
		exit;
	}

// validation
$talker=mysql_escape_string($talker);
$server=mysql_escape_string($server);
if (validate_date($tslice) == "f") { exit; }

$tslice_table='logdb_messages_'.$tslice.'_'.$xmpp_host;
$result=db_q(USER_ID,$server,$tslice_table,$talker,$search_p,"3",$start,$xmpp_host,20000);

$user_name=get_user_name($talker,$xmpp_host);
$server_name=get_server_name($server,$xmpp_host);
$nickname=$sess->get('export_nickname');

$lang=$sess->get('language');

header("Cache-Control: public, must-revalidate");
header("Pragma: hack"); // this is WEIRD - it is needed to work with Internet Explorer :O
header("Content-Type: application/octet-stream");
header("Content-Disposition: attachment; filename=\"Jorge_chat_$nickname-$tslice.txt\"");

$data="$export_head1[$lang]$nickname ($user_name@$server_name) $export_head2[$lang] $tslice:\n";

while ($results=mysql_fetch_array($result)) {

if ($results["direction"] == "from") 
			{ 
				$out=$nickname;
				$tt=$tt+1;
				$aa=0;
			} 
			else 
			{ 
				$out = TOKEN;
				$aa=$aa+1;
				$tt=0;
			}



		if ($aa<2 AND $tt<2) {
			
				$data .= "\n(".trim(strstr($results[ts], ' ')).") $out\n"; 
				$here="1"; 
			} 
			else 
			{ 
				$data .=""; $here="0"; 
			}

$data .="       $results[body]\n";

}

$data .="\n\n\nGenerated by Project Jorge @ 2008";

echo $data;
ob_end_flush();

$extra=mysql_escape_string("$user_name@$server_name ($tslice)");
$query="insert into jorge_logger (id_user,id_log_detail,id_log_level,log_time,extra) values ('".USER_ID."',8,1,NOW(),'$extra')";
mysql_query($query) or die;
$sess->unregister('export_nickname');

?>
