{"Jabber Account Registration","Registro de Cuenta Jabber"}.
{"New Password:","Contraseña nueva:"}.
{"Old Password:","Contraseña antigua:"}.
{"Password Verification:","Verificación de contraseña:"}.
{"Register a Jabber account","Registrar una cuenta Jabber"}.
{"Register","Registrar"}.
{"Server:","Servidor:"}.
{"The password of your Jabber account was succesfully changed.","La contraseña de tu cuenta Jabber se ha cambiado correctamente."}.
{"There was an error changing the password: ","Hubo un error cambiando la contraseña."}.
{"There was an error creating the account: ","Hubo uno error al crear la cuenta:"}.
{"There was an error deleting the account: ","Hubo un error borrando la cuenta."}.
{"This page allows to create a Jabber account in this Jabber server. Your JID (Jabber IDentifier) will be of the form: username@server. Please read carefully the instructions to fill correctly the fields.","Esta página de permite crear una cuenta Jabber este servidor Jabber. Tu JID (Jabber IDentificador) será de la forma: nombredeusuario@servidor. Por favor lee detenidamente las instrucciones para rellenar correctamente los campos."}.
{"This page allows to unregister a Jabber account in this Jabber server.","Esta página te permite borrar tu cuenta Jabber en este servidor Jabber."}.
{"Unregister a Jabber account","Borrar una cuenta Jabber"}.
{"Unregister","Borrar"}.
{"Username:","Nombre de usuario:"}.
{"Your Jabber account was succesfully created.","Tu cuenta Jabber se ha creado correctamente."}.
{"Your Jabber account was succesfully deleted.","Tu cuenta Jabber se ha borrado correctamente."}.
