{'../../ejabberd-dev/trunk/src/gen_mod', [{outdir, "../../ejabberd-dev/trunk/ebin"},{i,"../../ejabberd-dev/trunk/include"}]}.
{'src/ejabberd_xmlrpc',     [{outdir, "ebin"},{i,"../../ejabberd-dev/trunk/include"}]}.
