{'../../../ejabberd-dev/branches/ejabberd-2.0.x/src/gen_mod', [{outdir, "../../../ejabberd-dev/branches/ejabberd-2.0.x/ebin"},{i,"../../../ejabberd-dev/branches/ejabberd-2.0.x/include"}]}.
{'src/mod_statsdx',     [{outdir, "ebin"},{i,"../../../ejabberd-dev/branches/ejabberd-2.0.x/include"}]}.
{'src/mod_stats2file',     [{outdir, "ebin"},{i,"../../../ejabberd-dev/branches/ejabberd-2.0.x/include"}]}.
