<?php
/*
Jorge - frontend for mod_logdb - ejabberd server-side message archive module.

Copyright (C) 2007 Zbigniew Zolkiewski

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

*/
require("func.php");
require("lang.php");
require("sessions.php");
require("config.php");

ob_start();

// init session
$sess = new session;
$bazaj=db_e_connect($db_ejabberd);
if (check_registered_user($bazaj,$sess) != "t") { exit; }

db_connect($mod_logdb);

$token=$sess->get('uid_l');
$user_id=get_user_id($token,$xmpp_host);

if (!ctype_digit($user_id)) { exit; }

$e_string=$_GET['a'];

if ($e_string) {
		$variables = decode_url2($e_string,$token,$url_key);
		$tslice = $variables[tslice];
		$talker = $variables[talker];
		$server = $variables[server];
	}
	else {
		header('Location: main.php');
		exit;
	}

// validation
$talker=mysql_escape_string($talker);
$server=mysql_escape_string($server);
if (validate_date($tslice) == "f") { exit; }

$tslice_table='logdb_messages_'.$tslice.'_'.$xmpp_host;
$result=db_q($user_id,$server,$tslice_table,$talker,$search_p,"3",$start,$xmpp_host,20000);

$user_name=get_user_name($talker,$xmpp_host);
$server_name=get_server_name($server,$xmpp_host);
$nickname=query_nick_name($bazaj,$token,$user_name,$server_name);

$lang=$sess->get('language');

header("Cache-Control: public, must-revalidate");
header("Pragma: hack"); // this is WEIRD - it is needed to work with Internet Explorer :O
header("Content-Type: application/octet-stream");
header("Content-Disposition: attachment; filename=\"Jorge_chat_$nickname-$tslice.txt\"");

$data="$export_head1[$lang]$nickname ($user_name@$server_name) $export_head2[$lang] $tslice:\n";

while ($results=mysql_fetch_array($result)) {

if ($results["direction"] == 1) 
			{ 
				$out=$nickname;
				$tt=$tt+1;
				$aa=0;
			} 
			else 
			{ 
				$out = $token;
				$aa=$aa+1;
				$tt=0;
			}



		if ($aa<2 AND $tt<2) {
			
				$data .= "\n(".trim(strstr($results[ts], ' ')).") $out\n"; 
				$here="1"; 
			} 
			else 
			{ 
				$data .=""; $here="0"; 
			}

$data .="       $results[body]\n";

}

$data .="\n\n\nGenerated by Project Jorge @ 2007";

echo $data;


ob_end_flush();

?>
