{'../../ejabberd-dev/trunk/src/gen_mod', [{outdir, "../../ejabberd-dev/trunk/ebin"},{i,"../../ejabberd-dev/trunk/include"}]}.
{'src/mod_muc_admin',     [{outdir, "ebin"},{i,"../../ejabberd-dev/trunk/include"}]}.
