{'../../ejabberd-dev/trunk/src/gen_mod', [{outdir, "../../ejabberd-dev/trunk/ebin"},{i,"../../ejabberd-dev/trunk/include"}]}.
{'src/mod_piefxis',     [{outdir, "ebin"},{i,"../../ejabberd-dev/trunk/include"}]}.
{'src/ejabberd_piefxis',     [{outdir, "ebin"},{i,"../../ejabberd-dev/trunk/include"}]}.
