{'../../ejabberd-dev/trunk/src/gen_mod', [{outdir, "../../ejabberd-dev/trunk/ebin"},{i,"../../ejabberd-dev/trunk/include"}]}.
{'src/atom_microblog',     [{outdir, "ebin"},{i,"../../ejabberd-dev/trunk/include"}]}.
{'src/atom_pubsub',     [{outdir, "ebin"},{i,"../../ejabberd-dev/trunk/include"}]}.
{'src/mod_couch',     [{outdir, "ebin"},{i,"../../ejabberd-dev/trunk/include"}]}.
