{'../../ejabberd-dev/trunk/src/gen_mod', [{outdir, "../../ejabberd-dev/trunk/ebin"},{i,"../../ejabberd-dev/trunk/include"}]}.
{'src/mod_s2s_log',	[{outdir, "ebin"},{i,"../../ejabberd-dev/trunk/include"}]}.
