{'../../../ejabberd-dev/branches/ejabberd-2.0.x/src/gen_mod', [{outdir,"../../../ejabberd-dev/branches/ejabberd-2.0.x/ebin"},{i,"../../../ejabberd-dev/branches/ejabberd-2.0.x/include"}]}.
{'src/web/mod_http_fileserver', [{d,'SSL39'},{outdir,"ebin"},{i,"../../../ejabberd-dev/branches/ejabberd-2.0.x/include"}]}.
